name: dot_globe_example
description: Example app for the dot_globe package.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cupertino_icons: ^1.0.8
  dot_globe:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
